// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mSuZN0g-9oR_nun-bfWThH4deuCzGzM',
    appId: '1:700410046501:web:0bda64bec86ac17d4eb7cc',
    messagingSenderId: '700410046501',
    projectId: 'to-do-list-planner',
    authDomain: 'to-do-list-planner.firebaseapp.com',
    storageBucket: 'to-do-list-planner.firebasestorage.app',
    measurementId: 'G-LP9EM1EFZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRXvgCWD7Pnxc_YTQJts3dEFcNWguYZcw',
    appId: '1:700410046501:android:53e1d6da494d30a64eb7cc',
    messagingSenderId: '700410046501',
    projectId: 'to-do-list-planner',
    storageBucket: 'to-do-list-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAphYCWf70BNkklqzZZb3KV1R4E9T5wuiI',
    appId: '1:700410046501:ios:3573067e82283cb54eb7cc',
    messagingSenderId: '700410046501',
    projectId: 'to-do-list-planner',
    storageBucket: 'to-do-list-planner.firebasestorage.app',
    iosBundleId: 'com.afsheen.pinknote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAphYCWf70BNkklqzZZb3KV1R4E9T5wuiI',
    appId: '1:700410046501:ios:3573067e82283cb54eb7cc',
    messagingSenderId: '700410046501',
    projectId: 'to-do-list-planner',
    storageBucket: 'to-do-list-planner.firebasestorage.app',
    iosBundleId: 'com.afsheen.pinknote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8mSuZN0g-9oR_nun-bfWThH4deuCzGzM',
    appId: '1:700410046501:web:291eede935d2507c4eb7cc',
    messagingSenderId: '700410046501',
    projectId: 'to-do-list-planner',
    authDomain: 'to-do-list-planner.firebaseapp.com',
    storageBucket: 'to-do-list-planner.firebasestorage.app',
    measurementId: 'G-HSNWDD2ZFX',
  );
}
